site_name: DCS Web Editor User Manual
theme:
  name: material
  language: en
  palette:
    scheme: slate
  logo: assets/images/logo.png
  favicon: assets/images/fav.png
  features:
    
nav:
  - Getting Started: index.md
  - UI Tools: sections/uitools/uitools.md
  - Mission: sections/mission/mission.md
  - Map Options: sections/mapoptions/mapoptions.md
  - Units: sections/units/units.md
  - Waypoints: sections/waypoints/waypoints.md
  - Statics: sections/statics/statics.md
  - Triggers & Zones: sections/triggers/triggers.md
  - Drawings: sections/drawings/drawings.md
  - Templates: sections/templates/templates.md
  - Collaborate: sections/collaborate/collaborate.md
  - Plugins: sections/plugins/plugins.md
  - 3D Editor: sections/3deditor/3deditor.md
  - FAQ: sections/faq/faq.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/7G3qcmxmAX
    - icon: fontawesome/brands/github
      link: https://github.com/DCS-Web-Editor
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/DcsWebEditor


extra_css:
  - assets/css/extra.css
