site_name: DCS Web Editor User Manual
theme:
  name: material
  language: en
  palette:
    scheme: slate
  logo: assets/images/logo.png
  favicon: assets/images/fav.png
  features:
    
nav:
  - Getting Started: index.md
  - FAQ: faq.md
  - Editor:
    - Shortcuts & UI Tools: editor/uitools.md
    - Mission: editor/mission.md
    - Map Options: editor/mapoptions.md
    - Units: editor/units.md
    - Waypoints: editor/waypoints.md
    - Statics & Bullseyes: editor/statics.md
    - Triggers & Zones: editor/triggers.md
    - Drawings: editor/drawings.md
    - Templates: editor/templates.md
    - Collaborate: editor/collaborate.md
    - Plugins: editor/plugins.md
    - 3D Editor: editor/3deditor.md
  - Viewer:
    - Shortcuts & UI Tools: viewer/uitools.md
    - Main Panel: viewer/panel.md


extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/7G3qcmxmAX
    - icon: fontawesome/brands/github
      link: https://github.com/DCS-Web-Editor
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/DcsWebEditor


extra_css:
  - assets/css/extra.css
